include(
  "build-and-run-locally",
  "build-with-auth",
  "build-with-buildargs",
  "build-with-dockerignore",
  "run-exec-and-copy-locally",
  "run-with-data-volume",
  "push-and-pull-with-auth",
  "build-push-and-run-remotely",
  "issue-41",
  "issue-64",
  "run-with-user"
)
