include(
        "build-and-run-locally",
        "build-with-buildargs",
        "build-with-dockerignore",
        "run-exec-and-copy-locally",
        "run-with-data-volume",
        "publish",
        "push-and-pull-with-auth",
        "build-push-and-run-remotely",
        "container-lifecycle",
        "issue-41",
        "issue-64",
        "run-with-user")
